### PR TITLE
Cleanup and fixes for cluster_id change

### PR DESCRIPTION
**Pull request by detiber**
- Move debug_level into vars.yml and byo inventory
- change variables in cluster_hosts.yml to be g_\* and update playbooks to use
  those values directly instead of setting them indirectly
- added a new g_all_hosts entry in cluster_hosts to use in the update playbook
  instead of unioning all host types within the playbook
- added a cluster_hosts.yml for the byo playbook

### CODE REVIEW

**Comment by detiber** [comment]
@kwoodson I've tested the above changes with both aws and byo so far and everything that I expect to work is working as expected.

**Comment by kwoodson** [comment]
@detiber, I attempted to use the g_\* from file and it didn't work.  If you did it and it worked then I'm fine with going that route.

**Comment by detiber** [comment]
@kwoodson The trick was to use the relative paths as they appear from the included playbook rather than the playbook that does the include.

**Comment by kwoodson** [comment]
@detiber, awesome.  I'll merge this.

**Comment by detiber** [comment]
as an fyi, I've also tested against libvirt and everything appears functional there as well....  I haven't tested GCE or OpenStack

**Pull request merged**
